# Generated by Django 5.0.7 on 2024-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patientopdform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.IntegerField(blank=True, null=True)),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nf_scr", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("day", models.IntegerField(blank=True, null=True)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("age_group", models.CharField(blank=True, max_length=50, null=True)),
                ("week", models.IntegerField(blank=True, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=50, null=True)),
                ("signs_and_symptoms", models.TextField(blank=True, null=True)),
                (
                    "physical_examination_and_finding",
                    models.TextField(blank=True, null=True),
                ),
                ("investigation", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                (
                    "prescribed_medicine_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prescribed_medicine_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dosage", models.CharField(blank=True, max_length=255, null=True)),
                ("treatment_remark", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "patient_data",
                "managed": False,
            },
        ),
    ]
