# Generated by Django 5.0.7 on 2024-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="patientopdform",
            table="patientopdform",
        ),
    ]
