# Generated by Django 5.0.7 on 2024-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=30, null=True)),
                ("password", models.CharField(blank=True, max_length=30, null=True)),
                ("mobileno", models.CharField(blank=True, max_length=20, null=True)),
                ("role", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
